### ISSUE TITLE
Fix build error on pax-exam-helper

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-build-utils#16]
It seems the issue comes from failing to download some `org.eclipse.persistence` artifacts.

The build works when adding the following to the [shared Travis settings](https://github.com/daisy/maven-parents/blob/travis/settings.xml)

``` xml
<repository>
          <id>eclipselink</id>
          <name>EclipseLink Releases</name>
          <url>http://download.eclipse.org/rt/eclipselink/maven.repo</url>
          <releases>
            <enabled>true</enabled>
          </releases>
 </repository>
```

But it should ideally be fixed it in the IT tests themselves (adding a repository to the IT `setting.xml` didn’t work).

**Comment by bertfrees** [comment]
@rdeltour The tests work fine on Travis (and I don't see an EclipseLink repository in the shared Travis settings). I don't remember ever fixing this, but should we consider it fixed?

**Comment by rdeltour** [comment]
OK, fine by me.
